### ISSUE TITLE
Local display failed when connecting ipc with display monitors.

### ISSUE THREAD

**Issue by wujunkai166** [01org/libxcam#185] opened 2015-09-15 02:22 UTC
I've tried multiple display monitors and only Samsung monitor with model number BX2350 can run local display successfully.

**Comment by zjamy** [comment] 2015-10-13 02:19
It's in the test-device-manager, we did not reproduced, will fix it once it's reproduced.

**Comment by windyuan** [comment] 2016-02-01 07:19
can't reproduce. close it.

**Closed by windyuan** 2016-02-01 07:19 UTC
